### ISSUE TITLE
Verze pro xelatex

### ISSUE THREAD

**Issue by dan-zeman** [ufal/UFAL_poster#5]
Přeložit xelatexem to sice jde, aniž by to spadlo, ale použije se nějaký defaultní font, protože ten stanovený v `betterposter.cls` nefunguje. Navíc třeba české "č" uvedené v UTF-8 přímo bez makra se pak vůbec nezobrazí, zatímco pdflatex spolu s `\usepackage[utf8]{inputenc}` to zvládne. Jenže já bych občas rád použil i různá jiná písma a zkušenosti mi říkají, že pak už to bez xelatexu nepůjde.

Přišel někdo na to, jak to udělat?

**Comment by tomasmcz** [comment]
Pokud jde o práci s různými písmy, zkusil bych lualatex nebo xelatex.

**Comment by dan-zeman** [comment]
> Pokud jde o práci s různými písmy, zkusil bych lualatex nebo xelatex.

Sorry, měl jsem na mysli xelatex, ale z nějakýho důvodu mi tam to "e" vypadlo ... třikrát :)

**Comment by tomasmcz** [comment]
Aha, to mne napadlo, ale zjistil jsem, že existuje i nějaký xlatex :-D

Moje řešení by bylo

```
%% Font                                                                                                                                                                                
\ifxetex                                                                                                                                                                               
\RequirePackage{cmbright}                                                                                                                                                              
\RequirePackage[no-math]{fontspec}                                                                                                                                                     
\setmainfont{Lato}                                                                                                                                                                     
\else                                                                                                                                                                                  
\RequirePackage{cmbright}                                                                                                                                                              
\RequirePackage[default]{lato}                                                                                                                                                         
\RequirePackage[T1]{fontenc}                                                                                                                                                           
\fi 
```

když dostanu práva k zápisu (@tomkocmi ?), můžu sem nahrát větev, ve které jsem si to zkoušel. BTW poslední commit v masteru mi rozbije layout na 3 strany.

**Comment by dan-zeman** [comment]
> BTW poslední commit v masteru mi rozbije layout na 3 strany.

Už jsem na to taky přišel, reverted. Vlastně jsem do toho asi neměl hrabat, nějak mi nedošlo, že push access mám možná jen z pozice admina organizace.

V té současné implementaci je zřejmě něco špatně, alespoň podle dokumentace, ale nepodařilo se mi to dostrkat do funkčního stavu, tak bude lepší se vrátit k tomu jakž takž funkčnímu dosavadnímu.

**Comment by tomasmcz** [comment]
Vyřešeno v #6, diskusi o technických detailech můžeme případně pokračovat tam.
